[workspace]
authors = ["Brian Grenier <grenierb96@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max/"]
preview = ["pixi-build"]
description = "A json library for Mojo"
name = "emberjson"
platforms = ["osx-arm64", "linux-aarch64", "linux-64"]
version = "0.3.4"
license = "Apache-2.0"
license-file = "LICENSE"
homepage = "https://github.com/bgreni/EmberJson"
repository = "https://github.com/bgreni/EmberJson"

[tasks]
build = { cmd = "mojo precompile emberjson -o emberjson.mojoc" }
format = { cmd = "mojo format -l 80 ." }
test = { cmd = "python run_tests.py" }
build_bench = "mojo build bench.mojo"
bench = { cmd = "./bench && rm bench", depends-on=["build_bench"] }
bench_compare = { cmd = "./bench --print-relative && rm bench", depends-on=["build_bench"] }
bench_float = "mojo compare_algo.mojo"
bench_write_results = { cmd = "./bench --overwrite && rm bench", depends-on=["build_bench"] }
update_and_build = { cmd = "pixi update && pixi run test && pixi run build" }
precommit = { depends-on = ["format", "test", "test_python_compat", "fuzz"] }
update_and_test = "pixi update && pixi run test && pixi run bench_compare"
test_python_compat = "python python_compat.py"
fuzz = "mojo -D ASSERT=all fuzz.mojo"
gen_jsonl = "mojo -D ASSERT=all -D GEN_JSONL fuzz.mojo"
gen_large = "python tools/gen_large_datasets.py"
float_round_trip = { cmd = "mojo -D ASSERT=all -I . test_float_roundtrip.mojo" }

[dependencies]
mojo = ">=1.0.0,<1.1.0"



[package]
name = "emberjson"
version = "0.3.4"

[package.build]
backend = { name = "pixi-build-mojo", version = "0.2.*" }

[package.host-dependencies]
mojo-compiler = ">=1.0.0,<1.1.0"

[package.build-dependencies]
mojo-compiler = ">=1.0.0,<1.1.0"

[package.run-dependencies]
mojo-compiler = ">=1.0.0,<1.1.0"

